Symbolicate function calls in check_rseq errors
When check_rseq reports an error about a function call, it's opaque to
the user what function is being called:

    test_cxxtrace-with-assert-call: in critical section in function _ZN13cxxtr[snip]SC_:
      note: function starts at address:         0x4f0a08
      note: critical section starts at address: 0x4f0ab8
      note: critical section ends at address:   0x4f12dc (+2084 bytes)
      note: abort handler starts at address:    0x4f1307
      error: stack pointer modified at 0x4f0b7d: callq 0x4f8f0c
      error: stack pointer modified at 0x4f0b9b: callq 0x4092e0

Make check_rseq guess the name of the function being called, and put the
function name in its diagnostics:

    test_cxxtrace-with-assert-call: in critical section in function _ZN13cxxtr[snip]SC_:
      note: function starts at address:         0x4f0a08
      note: critical section starts at address: 0x4f0ab8
      note: critical section ends at address:   0x4f12dc (+2084 bytes)
      note: abort handler starts at address:    0x4f1307
      error: stack pointer modified at 0x4f0b7d: callq 0x4f8f0c // _ZNKSt6vec[snip]zeEv
      error: stack pointer modified at 0x4f0b9b: callq 0x4092e0 // __assert_fail@PLT