Fix test_processor_id_manual on GCC 8
Building test_processor_id_manual with GCC 8 fails:

  ld: test/test_processor_id_manual/CMakeFiles/test_processor_id_manual.dir/main.cpp.o: in function `cxxtrace_test::(anonymous namespace)::create_world_readable_temporary_file()':
  test/test_processor_id_manual/main.cpp:253: undefined reference to `std::filesystem::temp_directory_path[abi:cxx11]()'
  ld: test/test_processor_id_manual/main.cpp:263: undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
  ld: test/test_processor_id_manual/main.cpp:263: undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'

Using GCC 8's std::filesystem requires linking libstdc++fs.a. Link
against that library to fix the linking errors.